### PR TITLE
Update r.cson

### PR DESCRIPTION
**Pull request by guillaumechaumet**
Some changes from my fork.

### CODE REVIEW

**Comment by randy3k** [comment]
@guillaumechaumet 

you might want to rebase the changes and write a more meaningful commit message.

**Comment by guillaumechaumet** [comment]
Yeah. I'm still struggling with github interface.

**Comment by guillaumechaumet** [comment]
I don't know to cancel pull, merge correctly, etc

**Comment by randy3k** [comment]
You shouldn't use the GitHub interface to edit files. Instead, do the editing locally and push to your remote.

**Comment by Ikuyadeu** [comment]
This guide is clear https://guides.github.com/activities/forking/

**Comment by randy3k** [comment]
Is Github desktop able to do rebasing at all?

**Comment by Ikuyadeu** [comment]
No, If you want, need once close this and send new PR.
And rebasing after PR is not so good.

**Comment by guillaumechaumet** [comment]
Ok

**Comment by randy3k** [comment]
Though one can use the new Github PR feature "Squash and merge" to rebase now.

**Comment by Ikuyadeu** [comment]
Oops, I didn't know that.
Thank you for share.

**Pull request closed without merging**
